module.exports = {
  content: [
    "./src/**/*.{html,js,ts,jsx,tsx}",
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "bg-gradients-linear": "var(--bg-gradients-linear)",
        "neutral-10": "var(--neutral-10)",
        "neutral-30": "var(--neutral-30)",
        "neutralneutral-100": "var(--neutralneutral-100)",
        "neutralneutral-200": "var(--neutralneutral-200)",
        "neutralneutral-300": "var(--neutralneutral-300)",
        "neutralneutral-400": "var(--neutralneutral-400)",
        "neutralneutral-50": "var(--neutralneutral-50)",
        "neutralneutral-500": "var(--neutralneutral-500)",
        "neutralneutral-600": "var(--neutralneutral-600)",
        "neutralneutral-700": "var(--neutralneutral-700)",
        "neutralneutral-900": "var(--neutralneutral-900)",
        "primaryprimary-100": "var(--primaryprimary-100)",
        "primaryprimary-200": "var(--primaryprimary-200)",
        "primaryprimary-900": "var(--primaryprimary-900)",
        "pure-white-ffffff": "var(--pure-white-ffffff)",
        stroke: "var(--stroke)",
        "success-65c18c": "var(--success-65c18c)",
        white: "var(--white)",
        "white-2-fafafa": "var(--white-2-fafafa)",
        "yellow-ffc805": "var(--yellow-ffc805)",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        "body-b": "var(--body-b-font-family)",
        "body-l": "var(--body-l-font-family)",
        "body-l-b": "var(--body-l-b-font-family)",
        "body-l-m": "var(--body-l-m-font-family)",
        "body-m": "var(--body-m-font-family)",
        "body-r": "var(--body-r-font-family)",
        "body-SM": "var(--body-SM-font-family)",
        "body-too-small-m": "var(--body-too-small-m-font-family)",
        "body-too-small-r": "var(--body-too-small-r-font-family)",
        "bodysmall-sm": "var(--bodysmall-sm-font-family)",
        sans: [
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
      },
      boxShadow: { "drop-shadow": "var(--drop-shadow)" },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
  },
  plugins: [],
  darkMode: ["class"],
};
